version: '3'
services:
  app:
    build: .
    container_name: app
    #entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s ./.docker/entrypoint.sh
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  nginx:
    build: .docker/nginx
    environment:
      - PHP_HOST=app
      - PHP_PORT=9000
    restart: always
    container_name: nginx
    ports:
      - '8000:80'
    volumes:
      - ./public:/var/www/public
    networks:
      - app-network
    depends_on:
      - app
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network
  mysql:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    container_name: mysql
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
