version: '2.3'
services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
  nginx:
    build: .docker/nginx
    restart: always
    container_name: nginx
    ports:
      - '8000:80'
    volumes:
      - .:/var/www
    networks:
      - app-network
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network
  mysql:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    container_name: mysql
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - NTSQK_USER=root
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", 'mysql -u root -proot -D laravel -e "select count(table_name) > 0 from information_schema.tables;" -N -B']
      interval: 10s
      timeout: 10s
      retries: 4
networks:
  app-network:
    driver: bridge
